server:
  servlet:
    context-path: /wechat001/hui
  port: 9090
wechat:
  config:
    #微信appId
    appId: 
    #微信appSecret
    appSecret: 
    token:
    #配置一个文字的模板ID
    singleTemplateId:
    template:
      #早安模板
      morningTemplate:
        #模板ID
        templateId: 
        #是否关注的用户全发送，ture为是，当值为ture时，sendOpenId 为排除发送对象的微信用户，当值为false为否，sendOpenId为发送对象的微信用户
        allSend: true
        filterOpenIds:
        parameter:
          #这是默认的设置，如果有用户没设置参数，就按此参数
          default:
            #早安话语
            title: 早上好呀
            #你们的相遇时间
            meetDate: '2021-02-20'
            #居住地点，高德地图api下载查询 https://lbs.amap.com/api/webservice/download
            city: 东莞
            #东莞的cityCode代码
            cityCode: 441900

      #文字模板
      copywritingTemplate:
        templateId: 
        allSend: true
        filterOpenIds:
        parameter:
          default:
            city: 东莞
            cityCode: 441900

      #颜文字模板
      emoticonsTemplate:
        templateId: 
        allSend: true
        filterOpenIds:
        parameter:
          default:

      #中午模板
      MiddayTemplate:
        templateId: 
        allSend: true
        filterOpenIds:
        parameter:
          default:

      #晚安模板
      nightTemplate:
        templateId: 
        allSend: true
        filterOpenIds:
        parameter:
          default:
            nightcity: 东莞市


#第一次见面时间
First:
  Firstmeeting: 'xxxx-xx-xx'

# xuan
birthdayConf:
  birthdayDate: 'xxxx-xx-xx'

# hui
birthdayhui:
  birthdayhuiData: 'xx-xx'

