server:
  servlet:
    context-path: /wechat001/hui
  port: 9090

wechat:
  config:
    # 微信appId（必写）
    appId: 
    # 微信appSecret（必写）
    appSecret: 
    token:
    # 配置一个文字的模板ID
    singleTemplateId:
    template:
      # 早安模板
      morningTemplate:
        # 模板ID（必写）
        templateId: 
        # 是否关注的用户全发送，ture为是，当值为ture时，sendOpenId 为排除发送对象的微信用户，当值为false为否，sendOpenId为发送对象的微信用户
        allSend: true
        filterOpenIds:

        parameter:
          # 这是默认的设置，如果有用户没设置参数，就按此参数
          default:
            # 早安话语
            title: 早上好呀
            # 你们的相遇时间（必写）
            meetDate: ''
            # 居住地点，高德地图api下载查询 https://lbs.amap.com/api/webservice/download（必写）
            city: 城市名称
            # 城市名称的cityCode代码（必写）
            cityCode: 
            constellation: 星座（必写）

      # 颜文字模板
      emoticonsTemplate:
        templateId: （必写）
        allSend: true
        filterOpenIds:
        parameter:
          default:
            title: 1


# 获取天气的key
lbs:
  key: （必写）

#第一次见面时间（必写）
First:
  Firstmeeting: ''

#生日倒计时（必写）
birthdayConf:
  birthdayDate: ''

# 获取星座的Key
constellation:
  key: 
